# Generated by Django 5.2.8 on 2025-12-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
