# Generated by Django 5.2.8 on 2025-12-03 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_name', models.CharField(blank=True, default='Anonymous', max_length=70, null=True)),
                ('profile_address', models.TextField(blank=True, max_length=101, null=True)),
                ('profile_cover_photo', models.ImageField(blank=True, null=True, upload_to='cover-pics/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile-pics/')),
                ('profile_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True)),
                ('profile_dob', models.DateField(blank=True, null=True)),
                ('profile_language', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_creation_time', models.DateTimeField(auto_now_add=True)),
                ('profile_updated_time', models.DateTimeField(auto_now=True)),
                ('is_profile_archived', models.BooleanField(default=False)),
                ('is_profile_public', models.BooleanField(default=True)),
                ('is_profile_verified', models.BooleanField(default=False)),
                ('is_profile_featured', models.BooleanField(default=False)),
                ('is_profile_suspended', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(blank=True, related_name='profile_followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='profile_following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Info',
                'verbose_name_plural': 'Profile Infos',
                'ordering': ['-profile_creation_time'],
            },
        ),
    ]
