# Generated by Django 5.2.8 on 2025-12-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_profileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='profile_name_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
