# Generated by Django 4.2.16 on 2025-12-11 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_user_reset_otp_user_reset_otp_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_otp_created_at',
        ),
    ]
